### ISSUE TITLE
Broken in Alfred 3 :(

### ISSUE THREAD

**Issue by g4r37h** [mdreizin/chrome-bookmarks-alfred-workflow#11]
No bookmarks could be found under Alfred 3. Profiles can be found though, but re-selecting the user's profile does not fix the issue.

**Comment by mdreizin** [comment]
@g4r37h I will take a look, but don't have ETA. I have some plans to refactor it completely to fix all existing issues and also improve performance.

**Comment by g4r37h** [comment]
Thanks for the speedy reply. I hadn't noticed any of the other issues so would personally be happy if it was just made to work again. I'm tempted to revert to Alfred 2 at the moment.  :(

**Comment by mdreizin** [comment]
@g4r37h Good news! I have almost done refactoring, need to make some polishes and I hope I will release new version next (mid) week. I have covered new version up to 100%. Thanks for patience ;)

**Comment by mdreizin** [comment]
@g4r37h Please download new version from [releases](https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases) tab and let me know it works or not for you.

**Comment by g4r37h** [comment]
Thanks for the update. The plugin now seems to work, but not in the same way as before - previously it would only return URLs that contained the exact string that was typed - so the more specific you wrote it, the fewer results you got - but now it seems to return results that contain any of the letters so you get many more results. This is the way the endorsed plugin behaves but I actually preferred the old behaviour. Is there any chance of getting that back? Or maybe adding a config option to allow users to switch between the two options?

**Comment by mdreizin** [comment]
@g4r37h Please try https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/v0.1.1

**Comment by g4r37h** [comment]
So the filtering is now much better - exactly as it was in the old version.  :)

But things seem to break if I try to rename the shortcut from 'chrome' to 'ch', which because we all want access to our bookmarks as quickly as possible, is what I set the shortcut to on both the old version and on the endorsed plugin.

**Comment by mdreizin** [comment]
@g4r37h I will fix that.

**Comment by mdreizin** [comment]
@g4r37h Please wait for https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/v0.1.5
