### ISSUE TITLE
New version search bookmarks differently

### ISSUE THREAD

**Issue by hudochenkov** [mdreizin/chrome-bookmarks-alfred-workflow#13]
Issue continues from #9.

If I search for ”react” both an old and a new version (0.1.1) have same results. I want to narrow down results and specifying search query with another word  (“react redux”). Old version shows a result that has both “react” **and** “redux” in a bookmark, but a new version, I suppose, shows results that have “react” **or** “redux” in a bookmark.

Old version results (results are different):

![screen shot 2016-07-01 at 09 19 53](https://cloud.githubusercontent.com/assets/654597/16513380/f963c7c4-3f6c-11e6-8c5d-0bbe0d8ffe48.png)

![screen shot 2016-07-01 at 09 19 58](https://cloud.githubusercontent.com/assets/654597/16513382/fec34618-3f6c-11e6-92a6-33571a45cef8.png)

New version results (results are the same, but maybe it contains more search results):

![screen shot 2016-07-01 at 09 16 18](https://cloud.githubusercontent.com/assets/654597/16513390/096db742-3f6d-11e6-8891-f366d5bbf6b4.png)

![screen shot 2016-07-01 at 09 16 25](https://cloud.githubusercontent.com/assets/654597/16513396/0e20c1b2-3f6d-11e6-80b5-548b0c361cf9.png)

**Comment by mdreizin** [comment]
Please download new version from https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/v0.1.2

New version will be added automatically when travis finishes build https://travis-ci.org/mdreizin/chrome-bookmarks-alfred-workflow/builds/141552162

**Comment by hudochenkov** [comment]
Thank you for quick response and changes!

It's almost done :)

I have these links:

```
Building React Applications with Idiomatic Redux - Course by @dan_abramov @eggheadio
https://egghead.io/series/building-react-applications-with-idiomatic-redux

React and Redux Single Page Applications Resources — Medium
https://medium.com/@sapegin/react-and-redux-single-page-applications-resources-22cd859b0c1d#.8s1dsuqs0

Leveling Up with React: Redux | CSS-Tricks
https://css-tricks.com/learning-react-redux/

How to Build a Todo App Using React, Redux, and Immutable.js
https://www.sitepoint.com/how-to-build-a-todo-app-using-react-redux-and-immutable-js/

mxstbr/react-boilerplate: Quick setup for performance orientated, offline-first React.js applications featuring Redux, hot-reloading, PostCSS, react-router, ServiceWorker, AppCache, FontFaceObserver and Mocha.
https://github.com/mxstbr/react-boilerplate
```

When I'm searching `react redux` last link is not in results, but all other links are. But when I'm searching for `react Redux` all links in results including last one. Even `react edux` shows last link :)

Previous workflow show all five links for both `react redux` and `react Redux`.

**Comment by mdreizin** [comment]
@hudochenkov I have just fixed this issue. Please wait for `0.1.4`.

**Comment by hudochenkov** [comment]
Wow you're quick! Thank you! I use your workflow very often, thank you for saving my time :)
