### ISSUE TITLE
Include the parent folder name

### ISSUE THREAD

**Issue by robballou** [mdreizin/chrome-bookmarks-alfred-workflow#17]
Thank you for this workflow ... it's very helpful!

It would be helpful for me to have the parent folder name in the bookmark information. I'm not sure if it makes most sense in the title or subtitle but essentially have a lot of project folders with similar links. For example, most projects have a "Basecamp" link, so searching for "basecamp" turns up a lot of results and "[project] basecamp" doesn't turn up any.

**Comment by mdreizin** [comment]
@robballou Thanks for the feedback. I will try to find a way how to display breadcrumbs.

**Comment by matthew-groth** [comment]
Thanks for the workflow. I also think adding folders would be an improvement. Perhaps it could work in conjunction with the search, similar to how it works when we are searching directories on our computer.

**Comment by mdreizin** [comment]
@matthew-groth I'm busy right now and I will try to implement this feature as soon as possible ;)

**Comment by mdreizin** [comment]
@robballou @mgroth0 Now that feature is available in the latest version. Please download `0.2.0` version from https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases.

**Comment by fusillijerry89** [comment]
Can we please have a feature where we can search by folder name? For example, I have a bunch of bookmarks in different folders, for example "January-2020". I would like to be able to do something like "chrome January-2020/keyword" which would search the January-2020 folder for keyword.

Is this possible?
