### ISSUE TITLE
can't find any chrome canary bookmarks

### ISSUE THREAD

**Issue by nikitavoloboev** [mdreizin/chrome-bookmarks-alfred-workflow#18]
It finds chrome bookmarks perfectly fine. But trying to search through Canary script filter gives me this result : 

![2016-11-18 at 13 05](https://cloud.githubusercontent.com/assets/6391776/20429548/b1aa8bc0-ad8f-11e6-9515-f7de3e70e1ea.png)

Thank you for any help.

**Comment by mdreizin** [comment]
@nikitavoloboev Could you please run `canary-profiles` and choose your profile then try to search again.

**Comment by nikitavoloboev** [comment]
Oh, that worked. Thank you.
