### ISSUE TITLE
Cant edit keywords

### ISSUE THREAD

**Issue by durandom** [mdreizin/chrome-bookmarks-alfred-workflow#20]
I had to edit the .plist

This is what the workflow looks like in alfreds settings.
Seems it's missing most workflows.

<img width="874" alt="screen shot 2017-02-07 at 11 00 43" src="https://cloud.githubusercontent.com/assets/161888/22686529/b4b6d1e6-ed24-11e6-9e71-c843d6610aa8.png">

**Comment by mdreizin** [comment]
@durandom They are under the `Script Filter`, `Open URL` and `Push Notification`, because workflow is automatically generated. I don't use any offset to add some spaces between the set of items. Just drag them out.

**Comment by durandom** [comment]
Ahh, thats it. Maybe add some offset? 

Otherwise, thanks for this great workflow and fast response. Really appreciated 🙇

**Comment by mdreizin** [comment]
@durandom I will prepare a separate fix. I will update `info.plist` and it will contain `a data` dictionary with position of elements and you don't need to do that manually.

**Comment by mdreizin** [comment]
@durandom Please update to the latest version https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.6
