### ISSUE TITLE
Doesnt work for recent chrome

### ISSUE THREAD

**Issue by durandom** [mdreizin/chrome-bookmarks-alfred-workflow#21]
Was not working for me on chrome 56, osx sierra, alfred 3.3
Had to apply this patch https://github.com/Kelym/chrome-bookmarks-alfred-workflow/commit/0c00e65bae427be2f6cd6bbf12323afabee6e749

**Comment by mdreizin** [comment]
@durandom Please use `chrome-profiles` option and set you current profile, for instance `chrome-profile Default`.

We can't use full path `~/Library/Application Support/Google/Chrome/Default`, because `Default` profile name is automatically detected.

Any way I will try to identify issues with the latest Chrome.

**Comment by durandom** [comment]
cool, re-installing the workflow and setting the profile to default via `chrome-profiles` worked.
With the default setting to `Auto` it gives me this

<img width="569" alt="screen shot 2017-02-07 at 14 52 34" src="https://cloud.githubusercontent.com/assets/161888/22693818/22882c18-ed45-11e6-8e88-78812ff8d7c8.png">

**Comment by mdreizin** [comment]
@durandom I am working on this.

Could you please copy that error to clipboard?

Also you may use `Bug` icon, select `Log: All Information` and copy error from output.

**Comment by durandom** [comment]
Thats the output with `Auto`

```
[2017-02-07 15:01:06][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="true" arg="" uid=""><title>Auto (Active)</title><subtitle></subtitle><icon>img/chrome.png</icon></item><item valid="true" arg="Default" uid="Default"><title>Default</title><subtitle>~/Library/Application Support/Google/Chrome/Default</subtitle><icon>/Users/hild/Library/Application Support/Google/Chrome/Avatars/avatar_generic.png</icon></item></items>
[2017-02-07 15:01:14][ERROR: input.scriptfilter] Code 11: Exited with error code but no message
[2017-02-07 15:01:14][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory" uid="error"><title>cli</title><subtitle>Error: open /Users/hild/Library/Application Support/Google/Chrome/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by mdreizin** [comment]
@durandom As temporary workaround:

- open workflow in finder (please use dropdown menu in `Open in Finder` under workflow settings);
- Edit `browser.yml` manually and add `profileName: "Default"`:

```yaml
---
- id: "5f62cd88-0737-48db-a56a-c28761a4fcab"
  name: "chrome"
  fullName: "com.google.Chrome"
  description: "Google Chrome"
  path: "~/Library/Application Support/Google/Chrome"
  iconUrl: "img/chrome.png"
  profileName: "Default"

- id: "51ad66cf-5391-4b3d-98eb-9c96711b4dd3"
  name: "canary"
  fullName: "com.google.Chrome.canary"
  description: "Google Chrome Canary"
  path: "~/Library/Application Support/Google/Chrome Canary"
  iconUrl: "img/canary.png"
  profileName: "Default"

- id: "5c5a3de8-474a-42bf-99f6-c61f793a6625"
  name: "chromium"
  fullName: "org.chromium.Chromium"
  description: "Chromium"
  path: "~/Library/Application Support/Chromium"
  iconUrl: "img/chromium.png"
  profileName: "Default"
```

**Comment by durandom** [comment]
ok, thanks. But actually choosing `Default` via the options worked too. So thanks again for the awesome support

**Comment by mdreizin** [comment]
@durandom Please update to the latest version https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.6
