### ISSUE TITLE
How can I change the chrome profile path?

### ISSUE THREAD

**Issue by troyoung** [mdreizin/chrome-bookmarks-alfred-workflow#27]
in debug mode, i got this error: 
[2017-02-17 15:28:09][input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item valid="false" arg="open ~/Library/Application Support/Google/Chrome/Default/Bookmarks: no such file or directory" uid="error"><title>chrome-bookmarks</title><subtitle>Error: open /Users/allen/Library/Application Support/Google/Chrome/Default/Bookmarks: no such file or directory</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>"

in my computer, chrome profile path is "~/Library/Application Support/Google/Chrome/Profile 2/Bookmarks"
so, how can I change it?

**Comment by mdreizin** [comment]
Please use `chrome-profile` command to specify profile.

**Comment by troyoung** [comment]
Sorry, I can't find command 'chrome-profile', only 'chrome-bookmarks' and  'normalise' in bin directory.

**Comment by troyoung** [comment]
Oh, I run 'chrome-profiles Auto' in Alfred, and it works, thx a lot
