### ISSUE TITLE
macOS High Sierra 10.13 Beta (17A315i)

### ISSUE THREAD

**Issue by notDavid** [mdreizin/chrome-bookmarks-alfred-workflow#29]
Hi there, I upgrade to the current macOS Beta and I can't get your workflow to work. I'm not sure if this is due to an error in my setup/configuration or an incompatibility with the new version of macOS.

I tried manually running 
```./bin/chrome-bookmarks bookmarks "chromium" -query="xyz"```

which gives me this error:
```Segmentation fault: 11```

Any idea? Thanks :)

**Comment by mdreizin** [comment]
@notDavid Hello, I don't have macOS High Sierra and I can't test it on it. If you would like to help with fixing any issues on macOS High Sierra I would really appriciate your help.

**Comment by olojiang** [comment]
I suffer the same issue today, as I upgrade to High Sierra yesterday.

**Comment by mdreizin** [comment]
@notDavid @olojiang I have just upgraded to macOS High Sierra and tested it and it worked fine. I would suggest to specify your profile via `*-profile` command (please see https://github.com/mdreizin/chrome-bookmarks-alfred-workflow#options).

Also I would like to tell that Alfred now supports searching of Chrome bookmarks (please see https://www.alfredapp.com/blog/releases/alfred-3-5-released-bookmarks-high-sierra/) and you can use it as standalone solution.

**Comment by mdreizin** [comment]
@notDavid I have bumped `go` version which is compatible with macOS High Sierra. Please update to the latest version from https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/0.1.9
