### ISSUE TITLE
Bookmarklets support?

### ISSUE THREAD

**Issue by limacohen** [mdreizin/chrome-bookmarks-alfred-workflow#31]
Tried a few bookmarklets and they don't seem to be working at all right now.

**Comment by mdreizin** [comment]
@limacohen Could you explain what do you mean?

**Comment by limacohen** [comment]
Sure, let's say I have a bookmark(let) called "BuiltWith" with the URL "javascript:void(location.href='http://builtwith.com?'+location.href)". Simply enough, it works if I click it from Chrome's bookmarks menu. If I look it up with your workflow, I can find it but upon opening it, nothing happens (besides Chrome getting focus).

![screen shot 2017-10-10 at 2 19 34 pm](https://user-images.githubusercontent.com/541169/31400916-7c7cdc7e-adf1-11e7-88ee-8085ae1cb930.png)

**Comment by mdreizin** [comment]
@limacohen I use

```json
{
  "alfredworkflow" : {
    "config" : {
      "browser" : "com.google.Chrome",
      "spaces" : "",
      "url" : "{query}",
      "utf8" : true
    }
  }
}
```

and it seems that is limitation of that block.
