### ISSUE TITLE
filename misspelled

### ISSUE THREAD

**Issue by matthewmcgarvey** [mdreizin/chrome-bookmarks-alfred-workflow#47]
https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/blob/master/pkg/browsers/browser_repostitory.go

I don't have the go tooling to make the change myself, so just letting you know 👋

**Comment by mdreizin** [comment]
@matthewmcgarvey Do you mean that ‘Filename’ should be renamed to ‘FileName’. If no, could you please provide more details?

**Comment by matthewmcgarvey** [comment]
sorry for not being clear.  The name of the file is misspelled.  It should be renamed to `browser_repository.go`

**Comment by mdreizin** [comment]
@matthewmcgarvey oh, thank you very much. I am going to fix that filename.
