### ISSUE TITLE
It doesn't work in Chrome version 46.0.2490.80 (64-bit), Yosemite.

### ISSUE THREAD

**Issue by onestark** [mdreizin/chrome-bookmarks-alfred-workflow#7]
Not work in Chrome Version 46.0.2490.80 (64-bit), Yosemite. Someone can fit it ?

**Comment by mdreizin** [comment]
@onestark Thanks for reporting. I will take a look next week.

**Comment by merchantguru** [comment]
FYI, it works for me in Chrome Version 46.0.2490.80 (64-bit) El Capitan

**Comment by mdreizin** [comment]
@onestark I managed to find time to fix all existing issues and also improve perfs. New version will be released next week. Sorry for late response.

**Comment by mdreizin** [comment]
@onestark Please download new version from [releases](https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases) tab and let me know it works or not for you.
