### ISSUE TITLE
workflow.yml data?

### ISSUE THREAD

**Issue by mikemcduffie** [mdreizin/chrome-bookmarks-alfred-workflow#71]
I'm trying to add MS Edge Chromium to the workflow but cannot figure out where "bookmarkListId bookmarkOpenId profileListId profilelist" are derived from. I can't find any of the strings in file/dir names in my ~/Library.  Likewise searching for these terms or the Chromium strings in all the major search engines produced no relevant hits.

I wouldn't guess these are self-generated. What am I missing?

**Comment by mikemcduffie** [comment]
I think I figured it out. Generate new ids with uuidgen. Successfully added Edge & Edge Beta.

**Comment by PsCYcho** [comment]
@mikemcduffie - Any chance you're submitting a PR for that update, or could share the final build with your changes?  I was looking for exactly the same thing and saw your comment on the closed issues list.

**Comment by mikemcduffie** [comment]
@PsCYcho My changes are on my fork: [https://github.com/mikemcduffie/chrome-bookmarks-alfred-workflow](url).

**Comment by PsCYcho** [comment]
Awesome.  Thanks @mikemcduffie !

**Comment by nlnlnull** [comment]
@mikemcduffie 
Translation from Google
How do `bookmarkListId`` bookmarkOpenId` `profileListId`` profileSetId` be generated? Can you provide the following steps?
Thank you very much ~

**Comment by mikemcduffie** [comment]
@nlnlnull As I stated above I generated them with the command line tool uuidgen (located for me at /usr/bin/uuidgen), but a quick web search shows multiple online tools for generating 128 bit UUIDs as well as an Alfred Workflow. The key for me was figuring out they were UUIDs (Universally Unique IDentifiers: virtually guaranteed unique 128 bit IDs).

**Comment by nlnlnull** [comment]
@mikemcduffie 
Translation from Google
Thank you, if you don't tell me, I dare not imagine it is that simple.

**Comment by earthpyy** [comment]
I'm making a PR about Microsoft Edge support. Please check #80.
