### ISSUE TITLE
Dont find bookmarks

### ISSUE THREAD

**Issue by danielgomezrico** [mdreizin/chrome-bookmarks-alfred-workflow#8]
Im using Chrome: 47.0.2526.73 (64-bit) and I have it installed on `/opt/homebrew-cask/Caskroom/`

I checked on alfred debug and it prints 

`[STDERR: alfred.workflow.input.scriptfilter] /bin/bash: ./bin/normalise: Permission denied`

what can I do?

**Comment by mdreizin** [comment]
@danielgomezrico I'm sorry for very late response.

I had no time to fix all existing issues. I' working on new version and I'm going to release it next week.

As temporary workaround please run `chmod +x ./bin/normalise`

**Comment by mdreizin** [comment]
@danielgomezrico Please download new version from [releases](https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases) tab and let me know it works or not for you.

**Comment by danielgomezrico** [comment]
@mdreizin it is just for Alfred 3?

**Comment by mdreizin** [comment]
@danielgomezrico It should work for Alfred 2/3.

**Comment by danielgomezrico** [comment]
@mdreizin for Alfred 2 it says that is not compatible, I tested on Alfred 3 and it works. thanks

**Comment by mdreizin** [comment]
@danielgomezrico Thanks for update. I will find a way to make it work for Alfred 2.

**Comment by mdreizin** [comment]
Please see https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/pull/16.
