### ISSUE TITLE
Workflow is broken if one of the bookmarks have emoji in URL

### ISSUE THREAD

**Issue by hudochenkov** [mdreizin/chrome-bookmarks-alfred-workflow#9]
If one of the bookmarks have emoji in URL workflow stops working.

URL that cause the problem: http://una.im/svg-icons#💁

Debug log:

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main(list(alfred.args()))
  File "main.py", line 38, in main
    ), provider.get_bookmarks(query))
  File "/Users/aleks/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.8B50DA7F-34CB-4976-88F2-5661D922B7D9/lib/workflow/providers/provider_base.py", line 142, in get_bookmarks
    url_ratio = matcher.ratio(decode_url(url))
  File "/Users/aleks/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.8B50DA7F-34CB-4976-88F2-5661D922B7D9/lib/workflow/providers/provider_base.py", line 42, in decode_url
    return urllib2.unquote(url.decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 25-26: ordinal not in range(128)
```

Workflow version is the latest from Packal.
Alfred v2.8.2 (432).
Chrome 50.0.2638.0 dev (64-bit).

**Comment by mdreizin** [comment]
Hello Aleks,

Thanks a lot! I have some plans to improve chrome workflow and also fix
this issue, but I don't know eta.

Ср, 10 февр. 2016 г. в 11:12, Aleks Hudochenkov
notifications@github.com>:

**Comment by rahulpilani** [comment]
https://github.com/mdreizin/alfred-workflows/pull/10 fixes this issue

**Comment by mdreizin** [comment]
@hudochenkov I have been working on new version and I'm going to release it new week.

**Comment by mdreizin** [comment]
@hudochenkov @rahulpilani Please download new version from [releases](https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases) tab and let me know it works or not for you.

**Comment by hudochenkov** [comment]
Thank you for new version it works with unicode in URLs now! But it stop handle queries with multiple words. In previous version I can search “chrome react redux” and get results with both “react” and “redux” in bookmark. Now it's just not searching. “chrome react” works, but “chrome react redux” doesn't work.

**Comment by mdreizin** [comment]
@hudochenkov Could you please provide `name` and also `url` of these bookmarks?

**Comment by mdreizin** [comment]
@hudochenkov?

<img width="593" alt="screen shot 2016-07-01 at 2 34 14 am" src="https://cloud.githubusercontent.com/assets/279122/16507692/63f1ec26-3f34-11e6-9b51-ad5fd3965aea.png">

**Comment by mdreizin** [comment]
@hudochenkov Please try https://github.com/mdreizin/chrome-bookmarks-alfred-workflow/releases/tag/v0.1.1

**Comment by mdreizin** [comment]
@hudochenkov I will close this issues. Feel free to create a new issue if something doesn't work
